global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "spring-boot-app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["backend:8080"]

  - job_name: "docker"
    static_configs:
      - targets: ["host.docker.internal:9323"]
