version: "3.8"

services:
  backend-write:
    build:
      context: ./simple
      dockerfile: Dockerfile
    container_name: backend-write
    restart: always
    ports:
      - "${BACKEND_WRITE_PORT-8080}:8080"
    environment:
      - FRONT_URL=http://localhost:${FRONTEND_PORT-5173}/
      - RDB_URL=mysql://rdbms:3306/${RDB_DATABASE:-testdb}
      - RDB_USER=${RDB_USER:-user}
      - RDB_PASSWORD=${RDB_PASSWORD:-pw}
      - RDB_DRIVER_CLASS=com.mysql.cj.jdbc.Driver
    depends_on:
      - rdbms

  backend-read:
    build:
      context: ./simple-readonly
      dockerfile: Dockerfile
    container_name: backend-read
    restart: always
    ports:
      - "${BACKEND_READ_PORT-8000}:8000"
    environment:
      - MONGO_URL=mongodb://${MONGO_USER:-root}:${MONGO_PASSWORD:-example}@mongo:27017/
      - MONGO_DATABASE=${MONGO_DATABASE:-testdb}
    depends_on:
      - mongo

  frontend:
    build:
      context: ./simple-front
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "${FRONTEND_PORT-5173}:5173"
    environment:
      - BACKEND_WRITE_URL=http://backend-write:8080
      - BACKEND_READ_URL=http://backend-read:8000
    depends_on:
      - backend-write

  rdbms:
    image: mysql:8.0
    container_name: rdbms
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${RDB_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${RDB_DATABASE:-testdb}
      MYSQL_USER: ${RDB_USER:-user}
      MYSQL_PASSWORD: ${RDB_PASSWORD:-pw}
    ports:
      - "${RDB_PORT-3306}:3306"
    volumes:
      - ./db/data:/var/lib/mysql

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "${MONGO_PORT-27017}:27017"
    volumes:
      - ./db/mongo-data:/data/db
    environment:
      MONGO_ROOT_USERNAME: ${MONGO_USER:-root}
      MONGO_PASSWORD: ${MONGO_PASSWORD:-example}

  metric:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - "${METRIC_PORT-9090}:9090"
    volumes:
      - ./metric/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend-write

  dashboard:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "${DASHBOARD_PORT-3000}:3000"
    volumes:
      - ./metric/grafana:/var/lib/grafana
    depends_on:
      - metric
