info:
  app:
    name: my-simple-app
    version: 0.0.1

spring:
  application:
    name: simple

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      show-details: always
    prometheus:
      access: unrestricted
  prometheus:
    metrics:
      export:
        enabled: true
