info:
  app:
    name: my-simple-app
    version: 0.0.1
cors:
  allowed: ${FRONT_URL:http://localhost:5173}
spring:
  application:
    name: simple

  datasource:
    url: jdbc:${RDB_URL:mysql://localhost:3306/testdb}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${RDB_USER:user}
    password: ${RDB_PASSWORD:pw}
    driver-class-name: ${RDB_DRIVER_CLASS:com.mysql.cj.jdbc.Driver}
  jpa:
    hibernate:
          ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  metrics:
    enable:
      hikari: true

  endpoint:
    health:
      show-details: always
    prometheus:
      access: unrestricted

  prometheus:
    metrics:
      export:
        enabled: true