info:
  app:
    name: my-simple-app
    version: 0.0.1

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/testdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: user
    password: pw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
          ddl-auto: update
    properties:
      hibernate:
        hibernate.dialect:  org.hibernate.dialect.MySQL8Dialect
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27018/testdb?authSource=admin
  application:
    name: simple

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  metrics:
    enable:
      hikari: true

  endpoint:
    health:
      show-details: always
    prometheus:
      access: unrestricted

  prometheus:
    metrics:
      export:
        enabled: true