info:
  app:
    name: my-simple-app
    version: 0.0.1

spring:
  datasource:
    url: jdbc:${RDB_URL}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${RDB_USER}
    password: ${RDB_PASSWORD}
    driver-class-name: ${RDB_DRIVER_CLASS}
  jpa:
    hibernate:
          ddl-auto: update
  data:
    mongodb:
      uri: ${MONGO_URL}?authSource=admin
  application:
    name: simple

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  metrics:
    enable:
      hikari: true

  endpoint:
    health:
      show-details: always
    prometheus:
      access: unrestricted

  prometheus:
    metrics:
      export:
        enabled: true