version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pw
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql

  mongo:
    image: mongo:6.0
    container_name: my_mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
